# Project information
site_name: Allkun Raptor
site_author: Kudaw S.A.
site_description: Documentacion para Allkun Raptor

# Copyright
copyright: Copyright &copy; 2020 Kudaw S.A. All Rights Reserved

# Nav
nav:
  - Home: index.md
  - ES:
    - 3.4: 
      - Introducción: es/3.4/index.md
      - Registro de Cambios: es/3.4/release_notes.md
      - Guia de Instalación: es/3.4/install.md

  - EN:
    - 3.4: 
      - Introduction: en/3.4/index.md
    


# Configuration
theme: 
  name: material # readthedocs material
  #custom_dir: theme/material
  language: en # en es
  logo: assets/images/raptor.png
  favicon: assets/images/favicon.ico
  palette:
    primary: black
    accent: black
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - instant


# Extras
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/kudaw-latam
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/kudaw
    - icon: fontawesome/brands/github
      link: https://github.com/kudawdev
  current_version: 3.3
  lang: Es

extra_javascript:
- assets/js/theme.js
extra_css:
- assets/css/theme.css


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true


# Plugins
plugins:
    - search
#    - pdf-export:
#        verbose: false
#        combined: true
#        media_type: print
#        theme_handler_path: pdf/cinder.py
